Roll back changes to fix build process
w-pay/sdk-wpay-android pull request #15
Opened 2021-09-17 02:10 UTC by NedaRobatMeily

Reverting changes made in this issue: https://github.com/w-pay/sdk-wpay-android/issues/5

Why do we need these changes?
Currently the build process is broken from CI: https://jitpack.io/com/github/w-pay/sdk-wpay-android/v4.3.1/build.log

2021-09-17 03:03 UTC, applimatix approved these changes

2021-09-17 03:03 UTC, applimatix commented on sdk/build.gradle
> +
We can probably get rid of this now as we'll be using JitPack. We should probably remove it from the sdk-wpay-openapi-android repo as well.

2021-09-17 03:03 UTC, applimatix commented on sdk/build.gradle
> +
We can probably get rid of this now as we'll be using JitPack. We should probably remove it from the sdk-wpay-openapi-android repo as well.

2021-09-17 03:03 UTC, applimatix commented on sdk/build.gradle
> +
We can probably get rid of this now as we'll be using JitPack. We should probably remove it from the sdk-wpay-openapi-android repo as well.

2021-09-17 03:03 UTC, applimatix commented on sdk/build.gradle
> +apply plugin: 'maven'
We can probably get rid of this now as we'll be using JitPack. We should probably remove it from the sdk-wpay-openapi-android repo as well.

2021-09-17 03:03 UTC, applimatix commented on sdk/build.gradle
> +version "4.3.1"
Not sure if we'll still need these?

2021-09-17 03:52 UTC, kierans commented on sdk/build.gradle
> +version "4.3.1"
Good question. I think we need to see how JitPack does versioning.

2021-09-17 03:53 UTC, kierans requested changes
I agree with all Mike's comments, and the clean up should happen as part of this PR.

2021-09-17 03:54 UTC, applimatix commented on sdk/build.gradle
> +version "4.3.1"
As far as I'm aware it uses Git tags or Github releases

2021-09-20 01:45 UTC, kierans approved these changes

2021-09-20 01:57 UTC, merged