Define publication in Gradle to fix issue in CI not finding artifacts
w-pay/sdk-wpay-android pull request #20
Opened 2021-09-23 06:00 UTC by NedaRobatMeily

[Fix CI](https://github.com/w-pay/sdk-wpay-android/issues/5) by adding missing maven-publish plugin.

**Why do we need these changes?**
Currently the publish process is broken from CI: https://jitpack.io/com/github/w-pay/sdk-wpay-android/v4.4.2/build.log

Logs are showing ERROR: No build artifacts found. 

This PR solves that issue by defining publications following the [example from Jitpack](https://github.com/jitpack/android-example/blob/master/library/build.gradle)

2021-09-23 06:05 UTC, applimatix commented
Hey @NedaRobatMeily do you know if the groupId and artifactId can be used in identifying the dependency with JitPack? This could be of interest to @kierans for later on when we change the grouped and version.

2021-09-23 06:05 UTC, applimatix approved these changes

2021-09-23 06:27 UTC, NedaRobatMeily commented
> Hey @NedaRobatMeily do you know if the groupId and artifactId can be used in identifying the dependency with JitPack? This could be of interest to @kierans for later on when we change the grouped and version.

Based on the Jitpack docs I'd say yes: _"Your Maven group id is harvested from the top-level pom and then used to locate the installed artifacts"

2021-09-23 06:54 UTC, kierans commented
@NedaRobatMeily Do we still have a group id in the Gradle files anymore? If not can we put it back?

2021-09-23 07:59 UTC, NedaRobatMeily commented
> @NedaRobatMeily Do we still have a group id in the Gradle files anymore? If not can we put it back?

@kierans added it back, is this what you were after?

2021-09-27 00:07 UTC, kierans requested changes

2021-09-27 00:07 UTC, kierans commented on sdk/build.gradle
> +                groupId = 'au.com.wpay.village.sdk'
Why not just reference the `groupId` and `version` on lines 8-9?

2021-09-27 00:54 UTC, kierans approved these changes

2021-09-27 01:09 UTC, merged